language: python
python:
    - "2.7"
    - "3.6"
env:
    - DJANGO_VERSION=1.3.7
    - DJANGO_VERSION=1.4.20
    - DJANGO_VERSION=1.5.12
    - DJANGO_VERSION=1.6.11
    - DJANGO_VERSION=1.7.8
    - DJANGO_VERSION=1.8.2
    - DJANGO_VERSION=1.9.9
    - DJANGO_VERSION=1.10.1
install:
    - python setup.py develop
script:
    - bash test.sh
matrix:
  exclude:
    - python: "3.6"
      env: "DJANGO_VERSION=1.3.7"
    - python: "3.6"
      env: "1.4.20"
