language: python
python:
    - "2.7"
env:
    - DJANGO_VERSION=1.3.7
    - DJANGO_VERSION=1.4.20
    - DJANGO_VERSION=1.5.12
    - DJANGO_VERSION=1.6.11
    - DJANGO_VERSION=1.7.8
    - DJANGO_VERSION=1.8.2
    - DJANGO_VERSION=1.9.9
    - DJANGO_VERSION=1.10.1
install:
    - python setup.py develop
    - pip install django==$DJANGO_VERSION
script:
    - bash test.sh
matrix:
  include:
    - python: "3.3"
      env: DJANGO_VERSION=1.6.11
    - python: "3.3"
      env: DJANGO_VERSION=1.7.8
    - python: "3.3"
      env: DJANGO_VERSION=1.8.2
    - python: "3.4"
      env: DJANGO_VERSION=1.7.8
    - python: "3.4"
      env: DJANGO_VERSION=1.8.2
    - python: "3.4"
      env: DJANGO_VERSION=1.9.9
    - python: "3.4"
      env: DJANGO_VERSION=1.10.1
    - python: "3.4"
      env: DJANGO_VERSION=1.11
    - python: "3.5"
      env: DJANGO_VERSION=1.8.2
    - python: "3.5"
      env: DJANGO_VERSION=1.9.9
    - python: "3.5"
      env: DJANGO_VERSION=1.10.1
    - python: "3.5"
      env: DJANGO_VERSION=1.11.0
    - python: "3.6"
      env: DJANGO_VERSION=1.11.0
